/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mvpinclusaoproduto.view;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author kauac
 */
public class PrincipalProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalProdutoView
     */
    public PrincipalProdutoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblQuantProdutosCadastrados = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        menuGerenciarProdutos = new javax.swing.JMenu();
        menuIncluirProduto = new javax.swing.JMenuItem();
        menuListarProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Total de Produtos Cadastrados:");

        lblQuantProdutosCadastrados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuGerenciarProdutos.setText("Gerenciar Produtos");

        menuIncluirProduto.setText("Incluir produto");
        menuGerenciarProdutos.add(menuIncluirProduto);

        menuListarProduto.setText("Listar produto");
        menuGerenciarProdutos.add(menuListarProduto);

        jMenuBar.add(menuGerenciarProdutos);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblQuantProdutosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblQuantProdutosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel lblQuantProdutosCadastrados;
    private javax.swing.JMenu menuGerenciarProdutos;
    private javax.swing.JMenuItem menuIncluirProduto;
    private javax.swing.JMenuItem menuListarProduto;
    // End of variables declaration//GEN-END:variables

    public JMenuBar getjMenuBar() {
        return jMenuBar;
    }

    public JMenu getMenuGerenciarProdutos() {
        return menuGerenciarProdutos;
    }

    public JMenuItem getMenuIncluirProduto() {
        return menuIncluirProduto;
    }

    public JMenuItem getMenuListarProduto() {
        return menuListarProduto;
    }

    public JLabel getLblQuantProdutosCadastrados() {
        return lblQuantProdutosCadastrados;
    }
    
}
